### ISSUE TITLE
Help text and more descriptive error message on error creating journal

### ISSUE THREAD

**Issue by sidneygijzen** [pdfernhout/narrafirma#11]
Hello,

I was creating a new journal and attempted to create one with spaces in the journal name. I got a generic error saying that something went wrong, however taking a look at the node.js error server process output I saw the following 

`... Error: addJournalSync: journalIdentifier contains unacceptable characters like leading periods or slashes\n    at addJournalSync ...` 

So I assumed that special characters aren't allowed. I tried a name without spaces, such as `journal-without-spaces` which got created flawlessly.

My suggestion is to:
- let the user know what characters are allowed, e.g. with a help text or popup near the input field of the journal name
  - this can be improved by client side validation on entering the journal name
- improving the error message from the server by showing a more descriptive error message, e.g 'the following characters are not allowed in the journal name: ...'.

**Comment by cfkurtz** [comment]
Fixed this issue, sort of. Now in the admin interface, above the Journal name field, it says: 

> A journal name can have alphanumeric characters, underscores, dashes, and dots (one dot at a time). It cannot include spaces, forward slashes, two or more dots in a row, or non-alphanumeric characters.

See commit bf0e0a2b8f17e10021850b1613a8d4aea4e856f4

This _should_ be supported with validation, but the information should "keep a finger in the dam" until we get around to implementing that.
