### ISSUE TITLE
Checkboxes don't save values

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#12]
When I create a question about a story and select the 'checkboxes' type, the question is displayed properly on the story collection form for "Enter stories > Add Stories...". When I add a story (or "Import story data from CSV file into story collection ...) and then review incoming stories, all checkbox values are displayed, regardless of what was entered.

When I choose "Export story collection..." no values have been saved. The output looks like:

```
 Story title,Story text,Eliciting question,option1,option1,option1,option1,option1
 Checkbox Test,Check just the first option,Are checkboxes working?,,,,,
```

Note: I'm working with a git checkout of the v0.9.6 tag.

**Comment by cfkurtz** [comment]
Fixed this! It all came down to one misplaced assignment. 

See commit 429768caa9e9e25bc83d153c2bebd6f9053e73a4
