### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#13]
After pulling the latest commits to master (at 2a11f72d61d) and rebuilding narrafirma, I get the following error after running tsc from the narrafirma root directory. I haven't seen this one before and am not sure how significant it is. So, I mention it, but so far I haven't run into how it manifests, if at all, in the story browser as I'm working on data formatting first.

```
webapp/source/applicationWidgets/StoryBrowser.ts(407,83): error TS2345: 
Argument of type '{ "location": string; }' is not assignable to parameter of type 'Options'.
Object literal may only specify known properties, 
and '"location"' does not exist in type 'Options'.
```

**Comment by cfkurtz** [comment]
I think fa0d20107576cdcd3e77f5f499fc184ca7c23379 will fix that.
