### ISSUE TITLE
Questions about the user aren't labeled on the Review Incoming Story page

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#14]
I've created two fields about the user, a GroupID and a TellerID. When I fill out the form using NarraFirma or when I import data, either way, the field is displayed on the Review incoming stories form without the label and appear instead as:

```
[object Object]: 1000A // Where 1000A is the value that was entered in the text field
```

**Comment by cfkurtz** [comment]
Fixed. Was a result of adding a class for the story card field names, and in one case doing it wrong. b4688d2ca770045f27c6f19b565dce0b1bc854cb
