### ISSUE TITLE
The `tsc` package is now deprecated

### ISSUE THREAD

**Issue by bemosior** [pdfernhout/narrafirma#16]
The `tsc` NPM package [description page](https://www.npmjs.com/package/tsc) indicates that the package is now deprecated and includes instructions to make use of [`ntypescript`](https://www.npmjs.com/package/ntypescript). 

I gave `ntypescript` a try in #15, and it seemed to work.

@pdfernhout also mentions:

> We'd probably want to replace [tsc] with just the official "typescript" until I understand the benefits of "ntypescript" better as they apply to NarraFirma.

The official TypeScript repository is [here](https://github.com/Microsoft/TypeScript).

**Comment by pdfernhout** [comment]
@bemosior In the file "Install.md", we mention how to use "npm install -g typescript" to install the TypeScript compiler which is needed for building. So, there isn't currently a dependency on the npm "tsc" package that I see in package.json -- even though there is a  "tsc" command used there which is installed from the "typescript" package to run the compiler. I agree that if we improve the npm dependencies we should be careful to avoid deprecated npm packages like "tsc" and thanks for bringing this up. Both the "tsc" and "ntypescript" npm packages apparently provide APIs to use the TypeScript compiler directly from JavaScript code (which we don't currently do). If we wanted to include the TypeScript compiler itself, we would use the "typescript" npm package.

I'm closing this issue for now, but feel free to comment further on this if I am misunderstanding something and I will reopen it if needed.

**Comment by bemosior** [comment]
Makes sense, I think I misunderstood originally!
