### ISSUE TITLE
It would be nice to have button back to "all" projects

### ISSUE THREAD

**Issue by hvgard** [pdfernhout/narrafirma#23]
When I want to go back to "all" my projects I need to restart from wordpress instead of having a button that leads me back to the all projects overview.

<img width="1874" alt="schermafbeelding 2017-03-16 om 13 42 05" src="https://cloud.githubusercontent.com/assets/26460757/23997080/33d3fd3a-0a50-11e7-8aa0-212af74f3a98.png">

**Comment by cfkurtz** [comment]
Done in commit 2f26606a3c11d8f2549b815a1d440ef9e511bccf (and mistakes doing it fixed in two later commits). Now there is a "Choose another project" link in the main page for each project.
