### ISSUE TITLE
Back to Administration screen button?

### ISSUE THREAD

**Issue by sidneygijzen** [pdfernhout/narrafirma#26]
Hello,

Today I was testing a lot with importing story forms and entries. For every test session I would create a new project, so I had no interference from previous tests. So I had to switch back and forth between the 'project application' and the 'administration tool'. While working with the project application, I couldn't find an easy way back to the administration tool. E.g. by means of a button in the header. Of course I could get back by changing the URL to `admin.html` of `start`, but unfortunately that isn't the most user-friendly way. To illustrate: I had to restart the application to get back to the start screen, because I forgot what the URL's were actually called :-)

I hope I overlooked something, and there is a GUI element which does what I'm looking for. Otherwise my request is: a button or menu item to easily switch between the project application and the administration tool.

btw I'm using the NodeJS version of the application.

**Comment by cfkurtz** [comment]
Thanks Sidney! I am going to add this to the to-do list for my next "pulse" of work which is coming up very soon.

**Comment by sidneygijzen** [comment]
You're welcome Cynthia. Good to hear!

**Comment by cfkurtz** [comment]
This was fixed/addressed in release 1.2.0.
