### ISSUE TITLE
Suggestion: add time/trend graphs

### ISSUE THREAD

**Issue by hvgard** [pdfernhout/narrafirma#30]
When PNI is used to collect stories over time of periodically trends may emerge of changes may occur over time. Is there a way to handle that in NF?

**Comment by Salishsea86** [comment]
We have been doing that by adding a drop-down menu for the user to enter the month their story was entered.  Not a perfect workaround, and requires some hand correcting, but does the trick.  Timestamps for entries would be insanely useful as we are also using NarraFirma for longer range monitoring of trends and patterns.

**Comment by cfkurtz** [comment]
This feature is being added in NF 1.5.0. :)
