### ISSUE TITLE
Delected projects seems not really deleted

### ISSUE THREAD

**Issue by hvgard** [pdfernhout/narrafirma#32]
When I delete a project (using the Wordpress plugin) and later (sometimes months) add a new project with the same name, it turns out the old project is not deleted. How can I really delete a project. If only to avoid use of server diskspace.

**Comment by cfkurtz** [comment]
Yes, sorry. This was a bug. I have fixed it. You can now "Archive" a project, which will hide it from view correctly.

However, I still do not want to have a one-click option that destroys an entire project in a second. After all, in most NarraFirma use cases, projects don't take up much space on the server. It is only with massive projects that a space-clearing capability is needed. Preserving project data against accidental deletion is a more important requirement for most NF users.

So, to "really delete a project," you must (a) archive it, (b) entirely remove its definition from the JSON configuration list of project definitions, then (c) use a WordPress plugin to delete the database table associated with the project. There are several such plugins, and they are easy to install and use. For example, "WP Data Access" shows you all of your tables and allows you to "DROP" (delete) them from the WordPress database. Having to delete the actual database table outside of NarraFirma makes destroying a project just a little bit harder, which reduces the likelihood that people will do it accidentally. But it's still pretty easy.
