### ISSUE TITLE
Expand "save view box" to multiple lines

### ISSUE THREAD

**Issue by hvgard** [pdfernhout/narrafirma#33]
The save selection option is great, but the box for saved selections would benefit from being multiline instead of single line. 

<img width="1645" alt="Schermafbeelding 2020-06-22 om 16 04 56" src="https://user-images.githubusercontent.com/26460757/85297128-aee27600-b4a2-11ea-9c26-cfb99592a8aa.png">

**Comment by cfkurtz** [comment]
Done, will be released in version 1.5.0

**Comment by hvgard** [comment]
Thanks Cynthia. Looking forward to it.
