### ISSUE TITLE
/api/pointrel20150417 returns home page in WordPress instead of JSON

### ISSUE THREAD

**Issue by BurningDog** [pdfernhout/narrafirma#34]
Hi! I'm trying to install NarraFirma on Wordpress. https://wordpress.org/plugins/narrafirma/ says its tested up to Wordpress version 5.2.9 so I'm trying that first (even though latest Wordpress is 5.5.3).

I've followed the installation instructions and created a project. I have a single user (the administrator) and I've given that role access to SURVEY, READ and WRITE.

When I then click "Start NarraFirma" in `/wp/wp-admin/admin.php?page=narrafirma-settings-admin` it opens `/app/plugins/narrafirma/webapp/narrafirma.html` which does an AJAX call to `/api/pointrel20150417`

However, instead of that API call returning JSON it simply returns the home page of my wordpress site, which then results in this console error in `bundle-narrafirma.js` as it's trying to parse it as JSON:

`Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

I've tried to read the code in `narrafirma.php` to see how the API endpoint is registered but I'm not a wordpress developer so I'm guessing.

I _think_ `add_action( 'wp_ajax_pointrel20150417', 'NarraFirma\\pointrel20150417' );` is how it tells Wordpress to link the API call to the `function pointrel20150417()` - but that function is not called on the AJAX request.

Reading the WP developer docs at https://developer.wordpress.org/plugins/javascript/ajax/ is pretty unhelpful: `All WordPress Ajax requests must be sent to wp-admin/admin-ajax.php` but does that apply here?

**Comment by pdfernhout** [comment]
Hi Roger,

Thanks for the detailed bug report. Sorry you are encountering this issue.

To help troubleshoot this, here is a URL for a working installation of NarraFirma for WordPress:
https://narrafirma.com/wp-content/plugins/narrafirma/webapp/narrafirma.html#project=Blank%20NarraFirma%20project&page=dashboard

That installation makes an API call to this URL when accessing a regular non-admin project page: 
https://narrafirma.com/wp-admin/admin-ajax.php?action=pointrel20150417

The "/api/pointrel20150417" API you mention seems more typical for an install running under Node.js and not WordPress. The JavaScript code is supposed to figure out whether it is running under WordPress or Node.js and make the appropriate call. See: https://github.com/pdfernhout/narrafirma/blob/master/webapp/narrafirma.html#L16-L28

I am wondering if something has gotten broken somewhere along the line with that auto-detect feature either in your specific install or in general with some WordPress update?

**Comment by BurningDog** [comment]
Thanks for the reply - and apologies for my late response, I'm only coming back to this now.

https://narrafirma.com/wp-admin/admin-ajax.php?action=pointrel20150417 returns a JSON response (expected).

But on my site `/wp-admin/admin-ajax.php/?action=pointrel20150417` returns the home page of my site as html.

I'm going to keep digging. (This is on a fresh installation of both Wordpress 5.2.9 and NarraFirma 1.4.1).

**Comment by BurningDog** [comment]
Ah! I found the issue! I'm using [Bedrock](https://roots.io/bedrock/) to run Wordpress, as I prefer the 12 Factor App approach for web development, and the ability to use version control. This changes some paths. Wordpress is now available at `/wp` and plugs in in `/app/plugins`.

This changes the path of where NarraFirma is installed, and the `calculateAjaxPath()` function in `narrafirma.html` checks if it's installed on Wordpress by looking for `wp-content` in the url. But in Bedrock, plugins are installed in the `/app/plugins/` folder...which `calculateAjaxPath()` doesn't find and so thinks its running on nodejs.

There's probably a better way to check for Wordpress support, but this is a quick fix in the meantime:

```js
          var baseDirectoryPosition = path.indexOf("/wp-content/");
          var bedrockBaseDirectoryPosition = path.indexOf(
            "/app/plugins/narrafirma/"
          );
          if (baseDirectoryPosition !== -1) {
            window["ajaxurl"] =
              path.substring(0, baseDirectoryPosition) +
              "/wp-admin/admin-ajax.php";
            console.log("set ajaxurl to", window["ajaxurl"]);
          } else if (bedrockBaseDirectoryPosition !== -1) {
            window["ajaxurl"] = "/wp/wp-admin/admin-ajax.php";
            console.log("set ajaxurl to", window["ajaxurl"]);
          }
        }
```

I can PR this is you'd like?

**Comment by cfkurtz** [comment]
Hi, thank you so much for finding and posting this solution. I am sorry to have taken so long to get to this. Your approach seems reasonable! I have added it, in commit [c9c122d577a4b8868ce603badabbb7d10f45740c](https://github.com/pdfernhout/narrafirma/commit/c9c122d577a4b8868ce603badabbb7d10f45740c).
