### ISSUE TITLE
Why does NF show a project w/o anyone being logged in?

### ISSUE THREAD

**Issue by hvgard** [pdfernhout/narrafirma#38]
Hi Cynthia,

Today I updated to NF 1..5.1 and noticed that when I'm not logged in, the NF home screen shows:

<img width="1523" alt="Screenshot 2021-12-21 at 10 58 11" src="https://user-images.githubusercontent.com/26460757/146910554-fe1c5ae1-ed4f-4909-828a-772900b0b437.png">

Below is the JSON that is currenly in use:
{
    "NarraFirmaProject-Reigershoeve": {
        "write": [
            "admin_hvg",
            "Arno.Terra",
            "Harold.van.Garderen"
        ],
        "read": [
            ""
        ],
        "survey": [
            ""
        ]
    },
    "NarraFirmaProject-Passend onderwijs": {
        "write": [
            "admin_hvg",
            "Arno.Terra",
            "Harold.van.Garderen"
        ],
        "read": [],
        "survey": [
            ""
        ]
    },
    "NarraFirmaProject-TheBestIsYetToCome": {
        "write": [
            "admin_hvg",
            "Geert",
            "Arno.Terra",
            "Harold.van.Garderen"
        ],
        "read": [],
        "survey": [
            ""
        ],
        "archived": false
    }
}

Now I wonder why the "Reigershoeve" project is shown w/o anyone being logged in on nes.4vitea.nl

I noticed that the project shown is first one that has been added. So I edited the JSON to put  the "Best is yet" to come project first. That didn't solve anything. 

Next I noticed the 

        "survey": [
            ""
        ],

Instead of 
        "survey": [],

Then I edited the JSON once more to: 

{
    "NarraFirmaProject-TheBestIsYetToCome": {
        "write": [
            "admin_hvg",
            "Geert",
            "Arno.Terra",
            "Harold.van.Garderen"
        ],
        "read": [],
        "survey": [],
        "archived": false
    },
    "NarraFirmaProject-Reigershoeve": {
        "write": [
            "admin_hvg",
            "Arno.Terra",
            "Harold.van.Garderen"
        ],
        "read": [],
        "survey": []
    },
    "NarraFirmaProject-Passend onderwijs": {
        "write": [
            "admin_hvg",
            "Arno.Terra",
            "Harold.van.Garderen"
        ],
        "read": [],
        "survey": []
    }
}

Now the login screen shows: 

<img width="1091" alt="Screenshot 2021-12-21 at 12 52 33" src="https://user-images.githubusercontent.com/26460757/146925794-20a02481-a5a3-4af1-a28b-5c597e52d923.png">

So it seems NF processes "" and show at least one project when there are "" in the JSON.

**Comment by cfkurtz** [comment]
Thanks for troubleshooting this! Yes, it does appear that if you enter a WordPress user id or role in the "read" permission slot, and then remove it again, NF acts as if you have given anonymous read permission. We have replicated the bug on our test WordPress server. We cannot get it to happen for write permission, only for read. We are looking into what causes the error and should release a fix in the next few days. In the meantime, the workaround you found (removing the empty quotes) does seem to work.

**Comment by hvgard** [comment]
Hi, 

that makes sense. I never used “read” before. Today I did and …. bingo.

THANKS for chasing this with so much priority.

Harold

dr. Harold F. van Garderen
Architect opgavematig besturen, continue participatief evalueren en maatschappelijk verantwoorden

M	+31 6 2909 7305
E	***@***.***
W	www.4vitae.nl
T	@hvgard 
L	nl.linkedin.com/in/haroldvangarderen

**Comment by cfkurtz** [comment]
All right, we figured out where the problem was, and we have released a new version (1.5.7) with a fix. Please update your WordPress plugin to version 1.5.7. 

What happened was, we did not realize that when a user deleted the text of the HTML input field specifying a type of permission, it was not storing a null or other non-data value in that place, but an actual empty string (""). We also did not realize that the user id of an anonymous user visiting a WordPress site was also an empty string. So when we compared the two values, they matched. We had never happened to do that before (enter a value, then remove it), so we never saw the erroneous access happen. Now NF checks specifically to see if the field (any permission field) is an actual blank string.

Thanks again for noticing this and posting it.
