### ISSUE TITLE
Question short name truncated on export

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#4]
Expected behavior: When I enter a short name for a question about a story and export questions, I expect the whole name to be exported. 

Exhibited behavior: The short name for the "Eliciting question" is exported fully but the first two letters of short name of story questions are missing, at least for Radiobuttons, Scale, and Multiple choice. I've not tested other formats but imagine it's the same.

For example:
Technical becomes chnical
Communication becomes mmunication

Steps to reproduce: Write questions about stories, Design a story form that includes them, Start story collection, then export the story form. The same thing happens to them as labels when the story collection. 

They do look like they're being stored correctly:

**Comment by pdfernhout** [comment]
Thanks for reporting this. I previously added code that trims the first two letters of question IDs in some cases to remove the "S_", "P_" or "A_" prefixes used internally to distinguish different question types (Story, Participant, or Annotation). Likely I made a mistake somewhere and trim that in a case when I should not, resulting in the loss of information during export. I'll look into it right away.

**Comment by pdfernhout** [comment]
Thanks again for reporting this. This issue is fixed in v0.9.3.
