### ISSUE TITLE
Translation for write in answer prompts

### ISSUE THREAD

**Issue by Salishsea86** [pdfernhout/narrafirma#49]
When translating story forms, there is no option to translate the prompts for the open-ended options.  I think this must have been missed when that feature was added to the question types.

**Comment by Salishsea86** [comment]
Alos noticed that the "Does not apply" box under the sliders has no way to translate.

**Comment by cfkurtz** [comment]
Thank you so much for bringing these errors to my attention! I ... cannot look into them at the moment, but I promise to do so as soon as I can. If I forget, please remind me here or via email.

**Comment by Salishsea86** [comment]
Thanks!

**Comment by cfkurtz** [comment]
I finally got around to fixing this bug (in [version 1.6.6](https://narrafirma.com/2024/05/13/release-1-6-6)). The label for write-in answers is now included in the translation dictionary (for each question that has it).

However, I forgot to address the "Does not apply" issue (and only noticed it when I came here to tell you that I fixed the first thing). So I fixed it in [version 1.6.7.](https://narrafirma.com/2024/05/13/release-1-6-7/). 

Thank you for your patience!

**Comment by Salishsea86** [comment]
You are the best! Thanks so much.

____
CHRIS CORRIGAN
Blog and resources: http://www.chriscorrigan.com
Harvest Moon Consultants: https://www.harvestmoonconsultants.com

Upcoming events and workshops and online courses:
https://www.chriscorrigan.com/parkinglot/events/

Located on Nex̱wlélex̱wm (Bowen Island), Sḵwx̱wú7mesh-ulh territory,
