### ISSUE TITLE
Scale questions don't export scale labels

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#6]
Expected Behavior: When exporting story forms containing scale questions, I expect that the first two columns in "Answers" would be the left and right scale labels (in that order). 

Exhibited Behavior: Order, Long name, short name, Type, and About all have values, but there are no other values.

I'm not sure what I expect is exactly right, but I did figure that the labels would be somewhere in the export.

Steps to Reproduce: Add a scale question with left and right labels and export the story form.

**Comment by pdfernhout** [comment]
I have duplicated this bug and I will fix it. Thanks for reporting it!

**Comment by cfkurtz** [comment]
Fixed. It was not getting the correct data for sliders (scales). See commit cf995d18c67f89394b9f9b332dab121e58f702eb
