### ISSUE TITLE
Unexpected behavior for questions with HTML

### ISSUE THREAD

**Issue by pdfernhout** [pdfernhout/narrafirma#9]
This issues is to document unexpected behavior for HTML in questions mentioned via email by @eliza411. I am referring this to Cynthia to ensure this behavior is documented in the main help eventually.

To prevent cross-site scripting (XSS) risks when hosting projects for others, only certain HTML tags are allowed, and of those, no attributes are allowed. See sanitizeHTML.ts for a complete list of supported HTML tags (most of them, but without attributes).

Mostly this was just to support the use of `<strong>` which Cynthia thinks is essential when formatting questions. So, `<strong>` works as expected, as does `<bold>` and even `<table>` etc., but `<img src="x" onerror=alert("XSS")>` would fail. The system will report errors in such cases. Unfortunately, `<strong id='myid'>` or other innocuous things would also fail. It took a bit of work and a couple different tries to do that checking consistently just with tags (building on Mithril's inherently safe default behavior), and I hope it works correctly to prevent XSS risks.

Elaborating that approach to handle a restricted list of attributes (such as id) would be possible in theory, although at increased risk and effort. For example, here is a list of many things that can go wrong: [XSS Filter Evasion Cheat Sheet](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet). There are also more subtle issues though then like where img src fields might cause problematical requests to remote sites, including ones that pop up in-browser password request dialogs for basic authentication. So, I'm reluctant to go down the road of trying to figure out what attributes are safe and also, further, what values of the attributes are safe.

There is also special support in sanitizeHML.ts for using Mithril's dot notation to add css styling classes to tags, as in `<span.narrafirma-special-warning>`. However, those classes need to be whitelisted in the code. So far, the only one is "narrafirma-special-warning" used in the NarraFirma application itself. That style's meaning is hard-coded in the standard.css style sheet which is unavailable in surveys; that style is just used for the main application on one or two pages, and was a bit of a kludge. I'm not sure of all the risks and benefits for supporting custom CSS styling for surveys, and I would appreciate comments on that.

Still, I can see an argument that WordPress site owners should be able to decide whether to allow random HTML in their NarraFirma questions, either on a per-site or per-project basis, based on who was writing the questions. So, were we to host projects for others at NarraFirma.com, we would keep full HTML support in questions turned off (at least for other people's projects). But people hosting their own sites might want to turn it on, especially to embed images, videos, or various remote content (even iframes) in questions. I don't plan on adding a switch for general HTML support for a site or project right now, but people should feel free to make the feelings know on how important such support would be to them.

**Comment by cfkurtz** [comment]
I have added this information to the help system for questions about stories and participants:

> You can use these HTML tags: address, article, b, big, blockquote, br, caption, cite, code, del, div, dd, d1, dt, em, h1, h2, h3, h4, h5, h6, hr, i, kbd, li, ol, p, pre, s, small, span, sup, sub, strong, strike, table, td, th, tr, u, ul. 

I have also changed the code so that a smaller set of tags can be used for checkbox and radio button texts (in answers to questions). This also means that the same tags can be used in the texts of elicitation questions (which appear on the form as radio buttons beneath the "what question would you like to answer" question). The relevant help text for the smaller set of tags is this:

> You can also use a smaller subset of HTML tags (b, big, em, i, s, small, sup, sub, strong, strike, u) in your specified answers (choices) for checkboxes and radio buttons, and for eliciting questions.

See commit 46d959cc101ad33e7e49c88e33da9c0ec991accc
